### ISSUE TITLE
[jmf028] Display strucutres in all states in the puzzle page

### ISSUE THREAD

**Issue by jeehyung** [eternagame/EteRNA-public#107]

**Comment by jeehyung** [comment]
Must display all structures in Structure Notation panel

**Comment by jeejee85** [comment]
Do this for the "Lab puzzle" pages too - "/web/lab/{puznid}/

**Comment by lullujune** [comment]
Need an extra panel like Structure Notation panel in lab page too? or just add structures behind body?
