### ISSUE TITLE
[from:Brourd, hoglahoo] script searching options, edit, remove

### ISSUE THREAD

**Issue by kws4679** [eternagame/EteRNA-public#149]

**Comment by jeejee85** [comment]
Only show remove to my scripts
Add remove button to the individual script page
Add loading wheel overlay while deleting
Refresh instead "alert" when done deleting

**Comment by jeejee85** [comment]
Error when not logged in

**Comment by lullujune** [comment]
fixed

**Comment by lullujune** [comment]
deployed v2.04
