### ISSUE TITLE
[from:jandersonlee] Lab summary page to have more data : how many slots/votes left.

### ISSUE THREAD

**Issue by jeejee85** [eternagame/EteRNA-public#157]

**Comment by jandersonlee** [comment]
Also how many candidates submitted.

**Comment by lullujune** [comment]
implemented except how many candidates submitted

**Comment by jeejee85** [comment]
Solution submitted -> Designs you submitted
Vote -> Number of your votes (not left, but what you voted)

Don't show above two when not logged in

Only show slots left to admin
