### ISSUE TITLE
Use multiple icons for "lab" messages in the "My feed" page

### ISSUE THREAD

**Issue by jeejee85** [eternagame/EteRNA-public#171]
Lab messages have 2 types => "Design" & "vote". Right now they use the same icon (beaker + newspaper icon). Create another icon (either pick a license free image from the lab, or modify the current icon") and have 2 message types use different icons 

Reference : Diana (bokyung.seo.ai@gmail.com)

**Comment by b3h47pte** [comment]
Used the lab_vote.png image. :)
