### ISSUE TITLE
"Show thumbnail" button in the player profile "created puzzles" panel

### ISSUE THREAD

**Issue by jeejee85** [eternagame/EteRNA-public#172]
Add "Show thumbnail" in the player profile "created puzzles" page.

When you click on the button, the panel should display puzzle thumbnails along with their titles.

Puzzle thumbnail image URLs are

/sites/default/files/puzzle_mid_thumbnails/thumbnailXXX.png

where XXX is nid of the puzzle.

Reference : Diana (bokyung.ai.seo@gmail.com)

**Comment by iamadawra** [comment]
Functionality works but stylistic issues pending.

**Comment by iamadawra** [comment]
Resolved
