### ISSUE TITLE
community drop down link to wiki -bug

### ISSUE THREAD

**Issue by EdwardLane** [eternagame/EteRNA-public#183]
from some screens link  trys to hit http://ec2-54-242-172-93.compute-1.amazonaws.com/wiki/ from others it correctly goes to eterna wiki.org

so looks like the (flash?) title bar is not inherited, just ammended on a screen by screen basis

minor issue but should be quick to fix

Hello btw, thought I'd just flag this directly
Edward :)

**Comment by lullujune** [comment]
deployed v2.04
