### ISSUE TITLE
badge for helping with cloud lab beta (late 2012)

### ISSUE THREAD

**Issue by rhiju** [eternagame/EteRNA-public#197]
anytime we ask players to help test new features, award a badge for posting an issue or contacting us. for example, one important milestone was testing eterna 2.0 (cloud lab) -- let's make a special badge. perhaps these can be purple or red in that they can no longer be attained by other players.

**Comment by jeejee85** [comment]
Make a global variable : array of uids  and make the check function see if the uid is given in the global array. We'll edit this global array manually whenenver we want to give player a badge

**Comment by jeejee85** [comment]
Reference : Diana(bokyung.seo.ai@gmail.com)

**Comment by vineetsk1** [comment]
Here are some possible image designs:

Version 1 : https://dl.dropboxusercontent.com/u/184982878/beta_tester.png
Version 2 : https://dl.dropboxusercontent.com/u/184982878/beta_tester2.png
Version 3 : https://dl.dropboxusercontent.com/u/184982878/beta_tester3.png
Version 4 : https://dl.dropboxusercontent.com/u/184982878/beta_tester4.png

Here are some screenshots of how they look like on the site:
Version 1 : https://dl.dropboxusercontent.com/u/184982878/beta1.png
Version 2 : https://dl.dropboxusercontent.com/u/184982878/beta2.png
Version 3 : https://dl.dropboxusercontent.com/u/184982878/beta3.png
Version 4 : https://dl.dropboxusercontent.com/u/184982878/beta4.png

Sources:

Lab Beaker Icon : http://www.iconfinder.com/icondetails/171739/128/lab_icon
- License: Creative Commons Attribution 3.0 Unported (CC BY 3.0)

Cloud Icon : http://www.iconfinder.com/icondetails/110839/128/cloud_icon
- License: Free for commercial use

I adjusted/added color to the lab beaker icon, adjusted/added color to the cloud icon. The beta star is mine, with the font "Bebas" (freeware, usage in commercial or non-commercial works for free).

**Comment by vineetsk1** [comment]
Steven voted for Version 3, but wanted it to have a thicker outline, so here is Version 5:

Standalone image:
Version 5 : https://dl.dropboxusercontent.com/u/184982878/beta_tester5.png

How it looks like on the site:
Version 5 : https://dl.dropboxusercontent.com/u/184982878/beta5.png

Matt voted for Version 1.
