### ISSUE TITLE
badge for 1,000,000 points

### ISSUE THREAD

**Issue by jeejee85** [eternagame/EteRNA-public#199]

**Comment by b3h47pte** [comment]
Don't have an image though. Should I go on elance to find someone or will you do that Jee?

**Comment by jeejee85** [comment]
@b3h47pte Please tweak existing badge for now (don't spend too much time on this though). I'll look for the artist who'll handle Eterna in general

**Comment by jeejee85** [comment]
Can't find this badge on the roadmap - has it been added?

**Comment by b3h47pte** [comment]
@jeejee85  Woops I seemed to have wiped those changes when I was updating my repo. It's there again.

**Comment by jeejee85** [comment]
Will be verified when the art work is here

**Comment by lullujune** [comment]
deployed v2.04
