### ISSUE TITLE
badge for those with rank < 1000

### ISSUE THREAD

**Issue by jeejee85** [eternagame/EteRNA-public#201]
Reference : Justin (kws4679@gmail.com)

**Comment by steven123505** [comment]
For the record, this was my idea first: https://getsatisfaction.com/eternagame/topics/_new_badge_idea_rank_1000_badge

**Comment by Brourd** [comment]
Perhaps we should also include badges for reaching other rank milestones, such as top 500, top 100, top 50, top 25, etc.

**Comment by vineetsk1** [comment]
Functionality and placeholder design implemented.

Standalone Images:
Top 25 : https://dl.dropboxusercontent.com/u/184982878/top_25.png
Top 50 : https://dl.dropboxusercontent.com/u/184982878/top_50.png
Top 100 : https://dl.dropboxusercontent.com/u/184982878/top_100.png
Top 500 : https://dl.dropboxusercontent.com/u/184982878/top_500.png
Top 1000 : https://dl.dropboxusercontent.com/u/184982878/top_1000.png

Website Images (although it does not say coming soon but "go" or "locked"):
Top 25 : https://dl.dropboxusercontent.com/u/184982878/top_25_page.png
Top 50 : https://dl.dropboxusercontent.com/u/184982878/top_50_page.png
Top 100 : https://dl.dropboxusercontent.com/u/184982878/top_100_page.png
Top 500 : https://dl.dropboxusercontent.com/u/184982878/top_500_page.png
Top 1000 : https://dl.dropboxusercontent.com/u/184982878/top_1000_page.png

Image Sources:
http://www.iconfinder.com/icondetails/6709/128/green_red_user_icon
- Green user
  http://www.iconfinder.com/icondetails/6710/128/guy_red_user_icon
- Red user
  http://www.iconfinder.com/icondetails/6713/128/user_yellow_icon
- Yellow user
  http://www.iconfinder.com/icondetails/6711/128/pink_user_icon
- Pink user
  http://www.iconfinder.com/icondetails/6708/128/user_icon
- Blue user

All of the images I used were licensed by GPLv3.
