### ISSUE TITLE
Founder's badge 2

### ISSUE THREAD

**Issue by jeejee85** [eternagame/EteRNA-public#202]
Award "Founder's Badge 2" for helping with Eterna 2 game to players with UID <= 70906 (Those who registered before Feb, 2013)

**Comment by jeejee85** [comment]
@b3h47pte We had a big website change round Feb 2013. We want to thank everyone who played up to that point for sticking with us : ]

**Comment by b3h47pte** [comment]
Needs image.

**Comment by lullujune** [comment]
deployed v2.04
