### ISSUE TITLE
Individual Lab Page scoring scheme Panel

### ISSUE THREAD

**Issue by jeejee85** [eternagame/EteRNA-public#215]
Dropdown menu  to select scoring script
Score button pop up results

Only show this to active lab
Only show this if user is owner of the lab

**Comment by jeejee85** [comment]
Fix result box styling

**Comment by jeejee85** [comment]
Make it show to everyone

**Comment by jeejee85** [comment]
Add "Run on synthesized only" option. Check this by default

**Comment by lullujune** [comment]
released v2.01
