### ISSUE TITLE
Create embedded search mockup

### ISSUE THREAD

**Issue by afirst** [eternagame/EteRNA-public#23]
See email titled "Cloud lab roster page & project page". Look at CL project roster.

**Comment by jeehyung** [comment]
Make sure this fits in Cloud Lab page and the Player page. Look for mockups at Code-> jee_page_mockups

**Comment by afirst** [comment]
See https://docs.google.com/a/google.com/drawings/d/1tSmxEUDNJhNo4LJRXrmHej797HJeGdIezfpXphPOZ5U/edit
