### ISSUE TITLE
Integrate mat’s and jnicol’s cse tool in the game

### ISSUE THREAD

**Issue by lullujune** [eternagame/EteRNA-public#231]
-          sequence search tool
-          the other search fields are needed in game
  https://getsatisfaction.com/eternagame/topics/eterna_2_mockup_ideas#reply_10034795
  https://getsatisfaction.com/eternagame/topics/eterna_dreams#reply_6833950

**Comment by jeejee85** [comment]
Deferred - need to be somehow integrated with EternaScript query
