### ISSUE TITLE
An option to disable the chat box in the Flash areas of the site

### ISSUE THREAD

**Issue by ElNando888** [eternagame/EteRNA-public#243]
so, in puzzlemaker, lab designer, etc

**Comment by jeejee85** [comment]
Hi ElNando - we do have a chat hide function (a small arrow button next to the camera) in the flash areas. Did you mean other function than that?

**Comment by ElNando888** [comment]
Hi Jee,
If minimizing is the only option, I'd like it to stay minimized by default when I use any Flash page of the site. And yes, I would still like the box to actually disappear (semi)-permanently, until the day I have a 42" monitor, in which case I may not be annoyed by this box when creating/viewing large or multi-states puzzles for instance.
