### ISSUE TITLE
reorder badges for roadmap

### ISSUE THREAD

**Issue by vineetsk1** [eternagame/EteRNA-public#256]
reorder the achievements badges so that they don't cross over.

**Comment by vineetsk1** [comment]
I believe that this issue is not due to the ordering in achievements.json, but how the roadmap generates the tree.

For the 3 badges on the 2nd tier : "Become a Top Player", "Update your Profile", "Become a Puzzle Master" the first badge in achievements.json is displayed on the far left, but its connector is in the middle of the parent "Become an EteRNA Member". Thus, the other two must cross this one.

**Comment by jeejee85** [comment]
Closing - seems like we'll have to come up with a new layout algorithm
