### ISSUE TITLE
[from:jandersonlee] Make raw numbers for the raw SHAPE data available

### ISSUE THREAD

**Issue by jeehyung** [eternagame/EteRNA-public#26]

**Comment by dimenwarper** [comment]
We currently use the RDAT file format for sharing these data (e.g. take a look at an entry in the RMDB http://rmdb.stanford.edu/repository/detail/5SRRNA_SHP_0001 , in particular its RDAT file http://rmdb.stanford.edu/site_media/rdat_files/5SRRNA_SHP_0001/5SRRNA_SHP_0001_synced.rdat ), would this help? Files could be hosted in the RMDB or directly on EteRNA.

**Comment by jeehyung** [comment]
Make texts more visible

**Comment by jeehyung** [comment]
Make sure to get rid of unused texts

**Comment by jeejee85** [comment]
Solved by adding TSV downloadables. Closingl
