### ISSUE TITLE
Browse height bug

### ISSUE THREAD

**Issue by jeejee85** [eternagame/EteRNA-public#274]
http://lullujune.eternadev.org/web/browse/17320/

**Comment by jeejee85** [comment]
https://dl.dropboxusercontent.com/u/16417427/eterna_etc/eterna_bug.png

http://eterna.cmu.edu/web/browse/3191093/

This doesn't happen always

**Comment by lullujune** [comment]
This issue seems to be fixed in dev & product servers

**Comment by lullujune** [comment]
The problem occurred mainly at small screen devices(i.e. tablets, mac air 13 inch...)
It's been fixed now.

**Comment by lullujune** [comment]
released v2.01
