### ISSUE TITLE
synthesis  misspelled as syntheiss in proposed lab page

### ISSUE THREAD

**Issue by rhiju** [eternagame/EteRNA-public#287]
good test for rhiju in learning eterna code commit workflow.

**Comment by iamadawra** [comment]
I already implemented this in my workbranch a couple weeks back!

**Comment by iamadawra** [comment]
It never got verified by Jee. 
It's issue #253 

Either way, it's done now. :)

**Comment by rhiju** [comment]
Did you push? I don't see this fixed in the game. 
Rhiju

**Comment by jeejee85** [comment]
closing since this is a duplicate. Aayush's task will be updated.
