### ISSUE TITLE
make votes/ranks for proposed labs visible to all

### ISSUE THREAD

**Issue by rhiju** [eternagame/EteRNA-public#288]
we need to incentivize documentation of labs and projects, esp. by academic experts.

**Comment by lullujune** [comment]
released v2.02

**Comment by kws4679** [comment]
## NAVER - http://www.naver.com/

kws4679@naver.com 님께 보내신 메일 <Re: [EteRNA-public] make votes/ranks for proposed labs visible to all (#288)> 이 다음과 같은 이유로 전송 실패했습니다.

---

받는 사람이 회원님의 메일을 수신차단 하였습니다. 

---
