### ISSUE TITLE
Modularize email send function

### ISSUE THREAD

**Issue by jeejee85** [eternagame/EteRNA-public#290]
Make email_model.php in backend

Make sure to update eterna_autoload.php as well

**Comment by lullujune** [comment]
released v2.02

**Comment by kws4679** [comment]
## NAVER - http://www.naver.com/

kws4679@naver.com 님께 보내신 메일 <Re: [EteRNA-public] Modularize email send function (#290)> 이 다음과 같은 이유로 전송 실패했습니다.

---

받는 사람이 회원님의 메일을 수신차단 하였습니다. 

---
