### ISSUE TITLE
[from:stlnegril9 ] show the most recent solves/cleared puzzles in user profile page

### ISSUE THREAD

**Issue by kws4679** [eternagame/EteRNA-public#302]
https://getsatisfaction.com/eternagame/topics/cleared_puzzles_showing_oldest_first

**Comment by kws4679** [comment]
implemented

**Comment by lullujune** [comment]
released v2.02

**Comment by kws4679** [comment]
## NAVER - http://www.naver.com/

kws4679@naver.com 님께 보내신 메일 <Re: [EteRNA-public] [from:stlnegril9 ] show the most recent solves/cleared puzzles in user profile page (#302)> 이 다음과 같은 이유로 전송 실패했습니다.

---

받는 사람이 회원님의 메일을 수신차단 하였습니다. 

---
