### ISSUE TITLE
Picture upload doesn't work for lab proposal

### ISSUE THREAD

**Issue by jeejee85** [eternagame/EteRNA-public#312]
http://eterna.cmu.edu/web/propose/

Picture upload here doesn't work. This gets handled by eterna_post_controller "cloud_lab_puzzle" branch.

The upload works fine in the test server, but fails in the prod server.

Debug in the prod server. Please don't forget to delete test puzzles after you are done.

**Comment by lullujune** [comment]
Fixed. The file path was wrong, there was no "cloud_lab_pictures" folder, so created one for cloud lab images.
