### ISSUE TITLE
[from:stlnegril9 ] more script draw & animation functions

### ISSUE THREAD

**Issue by kws4679** [eternagame/EteRNA-public#313]

**Comment by kws4679** [comment]
gave him an example of drawing functions that can be integrated into script interface( raphael ). But I'm not sure they should be integrated since some of them can only be used in recent browsers ( they use html5 & canvas ) . I think it is better for users to use those functions on demand ( request those libraries by $.getScript whenever they need )

**Comment by lullujune** [comment]
released v2.02
