### ISSUE TITLE
[from:Eli Fisker] Keep message form

### ISSUE THREAD

**Issue by kws4679** [eternagame/EteRNA-public#319]
Eli Fisker → kws4679:  Hi Justin! Could you help us with another thing. When we write messages or comments, the periods and distance we make in our document, dissapears when we upload it. How can I keep the natural distance I make in a doc, when I post it: Example of structure dissapearing: http://prntscr.com/1kcpd8 Thx in advance.

**Comment by lullujune** [comment]
released v2.02
