### ISSUE TITLE
Lab follow links are broken

### ISSUE THREAD

**Issue by kws4679** [eternagame/EteRNA-public#323]
If I follow the lab and show the lab by "following puzzles" in my feed, link leads me to puzzle page, not lab page so image isn't appeared correctly.

**Comment by lullujune** [comment]
released v2.02

**Comment by kws4679** [comment]
## NAVER - http://www.naver.com/

kws4679@naver.com 님께 보내신 메일 <Re: [EteRNA-public] Lab follow links are broken (#323)> 이 다음과 같은 이유로 전송 실패했습니다.

---

받는 사람이 회원님의 메일을 수신차단 하였습니다. 

---
