### ISSUE TITLE
badge for contributing to wiki

### ISSUE THREAD

**Issue by vineetsk1** [eternagame/EteRNA-public#324]
Dr. Das noted today that we could have a badge for contributing to the wiki - might further incentivize the spread of the knowledge there..

**Comment by vineetsk1** [comment]
1 way would be to change the wiki login so it goes through drupal, but that sounds painful - http://www.mediawiki.org/wiki/Extension:AuthDrupal

Another way would be some kind of hamming string distance between the eterna username and the wiki username, along with an ip check to see if an eterna username and a wiki username are the same person, but this is definitely not accurate all the time

**Comment by lullujune** [comment]
Comment from Stlnegril9 :
I've no ideas for the badge, but agree with encouraging more EteRNA Wiki participation.
If the badge is created, perhaps the chat-bot could be modified to mention it. Something like "XYZ does not exist in the EteRNA Wiki, please create a definition. Earn a wiki contribution badge!"

-- vineet, after we set up whole things, could you put the last sentence("Earn a wiki contribution badge") in your bot?
