### ISSUE TITLE
[From: Edward] Filtering labs based on version of the synthesis was used

### ISSUE THREAD

**Issue by lullujune** [eternagame/EteRNA-public#356]
Edward_Lane: @dianaBK serious suggestion could we also seperate out based on 'which version of the synthesis was used - so we can 'ignore' old results when comparing with modern lab synthesis
if I look at this (for example) http://eterna.cmu.edu/web/player/34501/synthesized_RNAs/ or if I look at brourd's designs or whatever - some of them will have been made using modern and some using old lab synthesis techniques that make comparing them - like comparing apples to pears  [5:35 PM]
Edward_Lane: so being able to filter them out into date they were synthesised might be enough [5:36 PM]
flashtester: @Edward, okay I see, so, where do you want to use this filtering option? [5:41 PM]
Edward_Lane: hmm - anywhere there are a list of actually synthesised RNA (with results that didn't all get made at the same time) so the spot I notice the problem is on the pages like http://eterna.cmu.edu/web/player/34501/synthesized_RNAs/ but there are probably others

**Comment by edward** [comment]
I’ve just been accidentally mentioned in this comment thread, but I wanted to say that THIS GAME LOOKS AWESOME.

I miss bioinformatics.
