### ISSUE TITLE
[from:Eli Fisker] Eterna store

### ISSUE THREAD

**Issue by jeehyung** [eternagame/EteRNA-public#38]
> janelle: I want a T shirt [10:01 PM]
> janelle:  : ) [10:01 PM]
> Brourd: oooh, signed copies [10:01 PM]
> Brourd: and the T-shirt should be signed as well [10:01 PM]
> hurshy: you might be a geek if... [10:01 PM]
> Eli Fisker: Janelle, reminds me of what Hogla said the other day: I want a tshirt
> that says I solved the RNA Switch and all I got was this lousy tshirt. [10:02 PM]
> Eli Fisker: Honestly, I would want that too :) [10:02 PM]
> gooper20: lol, that would be awesome XD [10:02 PM]
> janelle: II's easr it! [10:02 PM]
> janelle: oops [10:03 PM]
> janelle: I'd wear it! [10:03 PM]
> gooper20: me too XD [10:03 PM]
> Eli Fisker: Hehe, I could suggest it to Adrien. No promises though [10:03 PM]
> gooper20: eterna needs a store! XD [10:04 PM]
> sixequalszero: shop.EteRNA [10:04 PM]
> Eli Fisker: Other that I'm sure it will make him laugh [10:04 PM]

**Comment by elifisker** [comment]
Mat mentioned to me that Foldit have a t-shirt and sent me the webadress on the company foldit used:  http://www.zazzle.com/foldit http://fold.it/portal/node/991221. Here is an example on their foldit products:
http://www.zazzle.com/foldit+gifts
