### ISSUE TITLE
Display SHAPE numbers

### ISSUE THREAD

**Issue by jeehyung** [eternagame/EteRNA-public#4]
from mat747

**Comment by jeehyung** [comment]
UPDATE : Allow users to have direct access to raw numbers

**Comment by mat747** [comment]
I still like the idea of having continuous colors for exp. data converted to numbers that can be displayed like in the cse tool (John data mining tool)

**Comment by lullujune** [comment]
round off the shape value to third decimal place

**Comment by lullujune** [comment]
deployed v2.04
