### ISSUE TITLE
TSV/RDAT prompt download instead of showing it in the browser

### ISSUE THREAD

**Issue by jeejee85** [eternagame/EteRNA-public#419]

**Comment by Omei** [comment]
As I recall, it used to prompt for download, and I actually liked the change to showing it in the browser.  What I didn't think about when I wrote the original issue is that I could get the source from the browser and cut and paste from it (or even save it in the rare case I wanted to) directly from the browser.

For me, at least, the normal use case is to immediately cut and paste the results into Excel.  So the extra step of asking the browser for the source is still more convenient than saving the file, importing it into Excel and then either deleting the file or moving it to a folder where I will be able to find it again.  

I'll vote for leaving it as it is now.
