### ISSUE TITLE
Add "easiest" sort option to player puzzles page

### ISSUE THREAD

**Issue by jeehyung** [eternagame/EteRNA-public#43]
http://eterna.cmu.edu/eterna_page.php?sort=date&page=playerpuzzles&pageindex=0

Add an option to sort puzzles based on reward points (refer to challenges puzzle page)

**Comment by kws4679** [comment]
finished & not yet deployed because of permission

**Comment by kws4679** [comment]
http://eterna.cmu.edu/eterna_page.php?sort=reward&page=playerpuzzles&workbranch=kws&pageindex=0
