### ISSUE TITLE
[from:Jennifer Pearl] Dot plot ticks

### ISSUE THREAD

**Issue by jeehyung** [eternagame/EteRNA-public#69]
https://getsatisfaction.com/eternagame/topics/idea_for_dot_plot_grid_coordinate_system_to_facilitate_discussions_about_dot_plots

**Comment by jeehyung** [comment]
http://kws.eternadev.org/game/puzzle/1009235/  

displays G twice

**Comment by jeehyung** [comment]
Numbers / Alphabets move

**Comment by kws4679** [comment]
done!!

**Comment by jeehyung** [comment]
ABCDEF display is off from line by several pixels
Overlay to show exact base numbers not just (A,10), (B,20), ...
