### ISSUE TITLE
[from:bentrem] provide pic/summary meta to googleplus/fb share crawlers

### ISSUE THREAD

**Issue by jeehyung** [eternagame/EteRNA-public#87]
https://getsatisfaction.com/eternagame/topics/improve_homepage_for_promotion

**Comment by jeehyung** [comment]
The issue has been updated to point to a correct getsat post

**Comment by BenTrem** [comment]
From jeehyung on #90:
"The server must provide pic/summary meta to the FB or G+ crawler when it tries to extract "promotion" pictures/texts."
