### ISSUE TITLE
[from:bentrem] Improve homepage for promotion

### ISSUE THREAD

**Issue by BenTrem** [eternagame/EteRNA-public#90]
https://getsatisfaction.com/eternagame/topics/improve_homepage_for_promotion

**Comment by BenTrem** [comment]
GPlus and FB use a simple method to extract images from linked pages. EteRNA's homepage fails in this respect.
see https://plus.google.com/104846054806852679393/posts/hkF6tztwRSK

I faked better results https://plus.google.com/104846054806852679393/posts/1DgBG2pJc99

**Comment by jeehyung** [comment]
This is exact equivalent to #87. The server must provide pic/summary meta to the FB or G+ crawler when it tries to extract  "promotion" pictures/texts. Closing.

**Comment by BenTrem** [comment]
Ah design decision?
Oh. Good to know.
